version: "3"

services:
    nestjs:
        container_name: octopy-api
        restart: always
        build: .
        ports:
            - "3000:3000"
        links:
            - mongo
    mongo:
        container_name: octopy-mongo
        image: mongo
        ports:
            - "27017:27017"